### ISSUE TITLE
最新版的是否已经修复Crosswalk 9.38.208.10 和 10.39.235.15 在MX3 flyme3.5.2 编辑html的时候有bug.的bug

### ISSUE THREAD

**Issue by brucewuu520** [GavinCT/Crosswalk#1]
最新版的是否已经修复Crosswalk 9.38.208.10 和 10.39.235.15 在MX3 flyme3.5.2 编辑html的时候有bug.的bug.可否及时同步啊

**Comment by GavinCT** [comment]
sorry,最新的没有再去试。  
 一个是因为去试的话我们的产品不稳定  
二是因为新增的功能我们基本用不到，新库也会让apk体积增大  

您有条件可以试一下告知我，谢谢

**Comment by brucewuu520** [comment]
好的，你们开发的是什么产品啊？ 我可以下载用用不？

**Comment by GavinCT** [comment]
为知笔记
